# Generated by Django 6.1.1 on 2026-09-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
